version: "3"
services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_CONN=root:root@tcp(db:3306)/mysql?charset=utf8&parseTime=true
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - fullstack
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql4aleck
      MYSQL_DATABASE: domains
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql4aleck
    ports:
      - "6033:3306"
    volumes:
      - "./db_data:/var/lib/mysql"
    networks:
      - fullstack
  web:
    build:
      context: ./frontend
      args:
        serverurl: ${EXTERNAL_IP}:8080
    ports:
      - "8090:80"
networks:
  fullstack:
    driver: bridge
